<div class="content-wrapper">

    <section class="content-header">
        <?php echo $this->partial('layout/breadcrumb'); ?>

        <h1 class="pull-right">
            <a href="<?php echo $this->url('sales-order-return');?>" class="btn btn-default btn-sm"><i class="fa fa-arrow-left"></i> <?php echo $this->translate('返回退货单列表'); ?></a>
            <button type="button" onclick="toPrint();" class="btn btn-primary btn-sm"><i class="fa fa-print" aria-hidden="true"></i> <?php echo $this->translate('点击打印'); ?></button>
            <?php echo $this->HelpUrl('salesOrderReturnList'); ?>
        </h1>
    </section>

    <section class="content">

        <div class="row">
            <div class="col-md-12" id="to-print-info">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title"><?php echo $this->translate('销售退货单');?></h3>
                    </div>

                    <div class="box-body">
                        <div class="row">
                            <div class="col-xs-4 form-group">
                                <div class="col-sm-12">
                                    <b><?php echo $this->translate('发货单号'); ?>：</b><?php echo $this->escapeHtml($this->returnInfo->getSalesSendOrderSn());?>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-xs-4 form-group">
                                <div class="col-sm-12">
                                    <b><?php echo $this->translate('销售单号'); ?>：</b><?php echo $this->escapeHtml($this->returnInfo->getSalesOrderSn());?>
                                </div>
                            </div>

                            <div class="col-xs-4 form-group">
                                <div class="col-sm-12">
                                    <b><?php echo $this->translate('退货状态'); ?>：</b><?php echo $this->salesHelper()->salesOrderReturnState($this->returnInfo->getReturnState(), 2); ?>
                                </div>
                            </div>

                            <div class="col-xs-4 form-group">
                                <div class="col-sm-12">
                                    <b><?php echo $this->translate('付款方式'); ?>：</b><?php echo $this->salesHelper()->orderReceivables($this->returnInfo->getOneSalesOrder()->getReceivablesCode());?>
                                </div>
                            </div>

                        </div>

                        <div class="row">
                            <div class="col-xs-4 form-group">
                                <div class="col-sm-12">
                                    <b><?php echo $this->translate('客户'); ?>：</b><?php echo $this->escapeHtml($this->returnInfo->getOneSalesOrder()->getOneCustomer()->getCustomerName());?>
                                </div>
                            </div>
                            <div class="col-xs-4 form-group">
                                <div class="col-sm-12">
                                    <b><?php echo $this->translate('客户联系人'); ?>：</b><?php echo $this->escapeHtml($this->returnInfo->getOneSalesOrder()->getCustomerContacts());?>
                                </div>
                            </div>

                            <div class="col-xs-4 form-group">
                                <div class="col-sm-12">
                                    <b><?php echo $this->translate('客户手机'); ?>：</b><?php echo $this->escapeHtml($this->returnInfo->getOneSalesOrder()->getCustomerPhone());?>
                                </div>
                            </div>

                        </div>

                        <div class="row">
                            <div class="col-xs-4 form-group">
                                <div class="col-sm-12">
                                    <b><?php echo $this->translate('客户座机'); ?>：</b><?php echo $this->escapeHtml($this->returnInfo->getOneSalesOrder()->getCustomerTelephone());?>
                                </div>
                            </div>
                            <div class="col-xs-8 form-group">
                                <div class="col-sm-12">
                                    <b><?php echo $this->translate('收货地址'); ?>：</b><?php echo $this->escapeHtml($this->returnInfo->getOneSalesOrder()->getCustomerAddress());?>
                                </div>
                            </div>

                        </div>

                        <div class="row">
                            <div class="col-xs-12 form-group">
                                <div class="col-sm-12">
                                    <b><?php echo $this->translate('退货备注'); ?>：</b><?php echo $this->escapeHtml($this->returnInfo->getSalesOrderReturnInfo());?>
                                </div>
                            </div>
                        </div>

                        <div class="box-header">
                            <h4 class="box-title"><?php echo $this->translate('退货商品'); ?></h4>
                        </div>
                        <div class="box-body table-responsive no-padding">
                            <table class="table table-hover">
                                <thead>
                                <tr>
                                    <th width="15%"><?php echo $this->translate('商品编号'); ?></th>
                                    <th width="20%"><?php echo $this->translate('商品名称'); ?></th>
                                    <th><?php echo $this->translate('商品规格'); ?></th>
                                    <th><?php echo $this->translate('单位'); ?></th>
                                    <th><?php echo $this->translate('销售单价'); ?></th>
                                    <th><?php echo $this->translate('退货数量'); ?></th>
                                    <th width="10%"><?php echo $this->translate('退货总价'); ?></th>
                                </tr>
                                </thead>

                                <?php
                                foreach ($this->orderGoods as $goodsValue) {
                                    ?>
                                    <tr>
                                        <td><?php echo $this->escapeHtml($goodsValue->getGoodsNumber());?></td>
                                        <td><?php echo $this->escapeHtml($goodsValue->getGoodsName());?></td>
                                        <td><?php echo $this->escapeHtml($goodsValue->getGoodsSpec());?></td>
                                        <td><?php echo $this->escapeHtml($goodsValue->getGoodsUnit());?></td>
                                        <td><?php echo $this->erpCurrencyFormat($goodsValue->getSalesGoodsPrice());?></td>
                                        <td><?php echo $this->escapeHtml($goodsValue->getGoodsReturnNum());?></td>
                                        <td><?php echo $this->erpCurrencyFormat($goodsValue->getGoodsReturnAmount());?></td>
                                    </tr>
                                <?php } ?>
                                <tfoot>
                                <tr>
                                    <td colspan="5"></td>
                                    <td colspan="2" class="text-right"><b><?php echo $this->translate('退货金额合计'); ?>：</b><span id="order-amount"><?php echo (isset($this->returnInfo) ? $this->erpCurrencyFormat($this->returnInfo->getSalesOrderReturnAmount()) : 0); ?></span></td>
                                </tr>
                                </tfoot>
                            </table>
                        </div>

                    </div>

                </div>


            </div>
        </div>

    </section>

</div>