<div class="content-wrapper">

    <section class="content-header">
        <?php echo $this->partial('layout/breadcrumb'); ?>

        <h1 class="pull-right">
            <?php echo $this->HelpUrl('salesSendOrderList'); ?>
        </h1>

    </section>

    <section class="content">
        <?php echo $this->partial('layout/messages'); ?>

        <div class="row">
            <div class="col-xs-12">
                <div class="box erp-box">

                    <div class="box-body table-responsive no-padding">
                        <table class="table table-hover">
                            <thead>
                            <tr class="erp-bg-thead">
                                <th width="10%"><?php echo $this->translate('发货单号'); ?>-<?php echo $this->translate('订单数：').$this->orderSendList->getTotalItemCount(); ?></th>
                                <th width="12%"><?php echo $this->translate('客户'); ?></th>
                                <th width="10%"><?php echo $this->translate('联系人'); ?></th>
                                <th width="10%"><?php echo $this->translate('联系电话'); ?></th>
                                <th width="10%"><?php echo $this->translate('收款方式'); ?></th>
                                <th width="10%"><?php echo $this->translate('收款金额'); ?></th>
                                <th width="6%"><?php echo $this->translate('状态'); ?></th>
                                <th width="6%"><?php echo $this->translate('退货'); ?></th>
                                <th width="15%"><?php echo $this->translate('操作'); ?></th>
                            </tr>
                            <?php
                            $sForm = $this->searchForm;
                            $sForm->prepare();
                            $sForm->get('sales_order_state')->setEmptyOption('选择');
                            $sForm->get('return_state')->setEmptyOption('选择');
                            ?>
                            <?php echo $this->form()->openTag($sForm); ?>
                            <tr>
                                <td>
                                    <?php echo $this->formElement($sForm->get('send_order_sn')); ?>
                                    <?php echo $this->formElementErrors($sForm->get('send_order_sn'), ['class'=>'error-message']);?>
                                </td>
                                <td>
                                    <?php echo $this->formElement($sForm->get('customer_id')); ?>
                                    <?php echo $this->formElementErrors($sForm->get('customer_id'), ['class'=>'error-message']);?>
                                </td>
                                <td>
                                    <?php echo $this->formElement($sForm->get('customer_contacts')); ?>
                                    <?php echo $this->formElementErrors($sForm->get('customer_contacts'), ['class'=>'error-message']);?>
                                </td>
                                <td>
                                    <?php echo $this->formElement($sForm->get('customer_phone')); ?>
                                    <?php echo $this->formElementErrors($sForm->get('customer_phone'), ['class'=>'error-message']);?>
                                </td>
                                <td>
                                    <?php echo $this->formElement($sForm->get('receivables_code')); ?>
                                    <?php echo $this->formElementErrors($sForm->get('receivables_code'), ['class'=>'error-message']);?>
                                </td>
                                <td>
                                    <p>
                                        <?php echo $this->formElement($sForm->get('start_amount')); ?>
                                    </p>
                                    <div>
                                        <?php echo $this->formElement($sForm->get('end_amount')); ?>
                                    </div>
                                    <?php echo $this->formElementErrors($sForm->get('start_amount'), ['class'=>'error-message']);?>
                                    <?php echo $this->formElementErrors($sForm->get('end_amount'), ['class'=>'error-message']);?>
                                </td>
                                <td>
                                    <?php echo $this->formElement($sForm->get('sales_order_state')); ?>
                                    <?php echo $this->formElementErrors($sForm->get('sales_order_state'), ['class'=>'error-message']);?>
                                </td>
                                <td>
                                    <?php echo $this->formElement($sForm->get('return_state')); ?>
                                    <?php echo $this->formElementErrors($sForm->get('return_state'), ['class'=>'error-message']);?>
                                </td>
                                <td>
                                    <button type="submit" class="btn btn-info btn-sm"><i class="fa fa-search"></i></button>
                                    <?php
                                    $formData = $sForm->getData();
                                    if(!empty(array_filter($formData)) || $formData['return_state'] != '') { ?>
                                        <a href="<?php echo $this->url('sales-send-order');?>" class="btn btn-default btn-sm"><i class="fa fa-reply"></i></a>
                                    <?php } ?>
                                </td>
                            </tr>
                            <?php echo $this->form()->closeTag(); ?>
                            </thead>

                            <?php if($this->orderSendList) foreach ($this->orderSendList as $order) { ?>
                                <tr>
                                    <td><?php echo $this->escapeHtml($order->getSendOrderSn()); ?></td>
                                    <td><?php echo $this->escapeHtml($order->getOneSalesOrder()->getOneCustomer()->getCustomerName()); ?></td>
                                    <td><?php echo $this->escapeHtml($order->getOneSalesOrder()->getCustomerContacts()); ?></td>
                                    <td><?php echo $this->escapeHtml($order->getOneSalesOrder()->getCustomerPhone()); ?></td>
                                    <td><?php echo $this->salesHelper()->orderReceivables($order->getOneSalesOrder()->getReceivablesCode()); ?></td>
                                    <td><?php echo $this->erpCurrencyFormat($order->getOneSalesOrder()->getSalesOrderAmount());?></td>
                                    <td><?php echo $this->salesHelper()->salesOrderState($order->getOneSalesOrder()->getSalesOrderState(), 2); ?></td>
                                    <td><?php echo ($order->getReturnState() == 1 ? '<b class="text-danger">'.$this->translate('有').'</b>' : $this->translate('无')); ?></td>
                                    <td>
                                        <a href="<?php echo $this->url('sales-send-order',
                                            ['action'=>'view', 'id'=>$order->getSendOrderId()]); ?>"
                                           class="btn btn-xs btn-info"><i class="fa fa-info-circle"></i> <?php echo $this->translate('查看'); ?>
                                        </a>
                                        <?php if ($order->getOneSalesOrder()->getSalesOrderState() == 6) { ?>
                                        <a href="<?php echo $this->url('sales-send-order', ['action'=>'finishSalesOrder', 'id'=>$order->getSendOrderId()], ['query' => ['qToken' => $this->common()->getCsrfValue()]]); ?>" class="btn btn-xs btn-success"><i class="fa fa-check"></i> <?php echo $this->translate('确认收货'); ?></a>
                                        <a href="<?php echo $this->url('sales-order-return',
                                            ['action'=>'add', 'id'=>$order->getSendOrderId()]); ?>" class="btn btn-xs btn-primary"><i class="fa fa-share"></i> <?php echo $this->translate('退货'); ?></a>
                                        <?php } ?>
                                    </td>
                                </tr>
                            <?php } ?>
                        </table>
                    </div>
                    <div class="box-footer clearfix">
                        <?php echo $this->paginationControl($this->orderSendList, 'Sliding', 'layout/page', ['route' => 'sales-send-order']); ?>
                    </div>
                </div>

            </div>
        </div>

    </section>
</div>