<div class="content-wrapper">

    <section class="content-header">
        <?php echo $this->partial('layout/breadcrumb'); ?>

        <h1 class="pull-right">
            <a href="<?php echo $this->url('brand', ['action'=> 'add']);?>" class="btn btn-primary btn-sm"><i class="fa fa-plus"></i> <?php echo $this->translate('添加品牌'); ?></a>
            <?php echo $this->HelpUrl('brandList'); ?>
        </h1>

    </section>

    <section class="content">
        <?php echo $this->partial('layout/messages'); ?>

        <div class="row">
            <div class="col-xs-12">
                <div class="box erp-box">

                    <form method="post" action="<?php echo $this->url('brand', ['action' => 'updateAll']);?>" name="edit-all-form" id="edit-all-form">
                    <div class="box-body table-responsive no-padding">
                        <table class="table table-hover">
                            <thead>
                            <tr class="erp-bg-thead">
                                <th width="2%"><input type="checkbox" class="minimal select-all-checkbox"></th>
                                <th>ID</th>
                                <th><?php echo $this->translate('品牌名称'); ?></th>
                                <th><?php echo $this->translate('品牌编码'); ?></th>
                                <th width="8%"><?php echo $this->translate('排序'); ?></th>
                                <th width="18%"><?php echo $this->translate('操作'); ?></th>
                            </tr>
                            </thead>

                            <?php if($this->brandList) foreach ($this->brandList as $brand) { ?>
                                <tr>
                                    <td><input  name="select_id[]" value="<?php echo $brand->getBrandId(); ?>" type="checkbox" class="minimal"></td>
                                    <td><?php echo $brand->getBrandId(); ?></td>
                                    <td><?php echo $this->escapeHtml($brand->getBrandName()); ?></td>
                                    <td><?php echo $this->escapeHtml($brand->getBrandCode()); ?></td>
                                    <td><input type="text" name="brand_sort[<?php echo $brand->getBrandId(); ?>]" value="<?php echo $brand->getBrandSort(); ?>" class="form-control input-sm"></td>
                                    <td>
                                        <a href="<?php echo $this->url('brand',
                                            ['action'=>'edit', 'id'=>$brand->getBrandId()]); ?>"
                                           class="btn btn-xs btn-success"><i class="fa fa-pencil"></i> <?php echo $this->translate('编辑'); ?>
                                        </a>

                                        <a href="javascript:;" onclick="deleteConfirm('<?php echo $this->translate('您确实要删除该商品品牌吗？'); ?>', '<?php echo $this->url('brand', ['action'=>'delete', 'id'=>$brand->getBrandId()], ['query' => ['qToken' => $this->common()->getCsrfValue()]]); ?>');" class="btn btn-xs btn-danger">
                                            <i class="fa fa-trash"></i> <?php echo $this->translate('删除'); ?>
                                        </a>

                                    </td>
                                </tr>
                            <?php } ?>
                        </table>
                    </div>
                    <div class="box-footer clearfix">
                        <input type="checkbox" class="minimal select-all-checkbox"> <?php echo $this->translate('全选'); ?>
                        <select name="editAllState" class="form-control input-sm" style="width: 120px;display: inline;">
                            <option value=""><?php echo $this->translate('选择状态'); ?></option>
                            <option value="sort"><?php echo $this->translate('更新排序'); ?></option>
                        </select>
                        <button type="submit" class="btn btn-primary btn-sm"><i class="fa fa-check"></i> <?php echo $this->translate('更新'); ?></button>
                    </div>
                    </form>
                </div>

            </div>
        </div>

    </section>
</div>