<div class="content-wrapper">

    <section class="content-header">
        <?php echo $this->partial('layout/breadcrumb'); ?>

        <h1 class="pull-right">
            <?php echo $this->HelpUrl('orderReturnList'); ?>
        </h1>

    </section>

    <section class="content">
        <?php echo $this->partial('layout/messages'); ?>

        <div class="row">
            <div class="col-xs-12">
                <div class="box erp-box">

                    <div class="box-body table-responsive no-padding">
                        <table class="table table-hover">
                            <thead>
                            <tr class="erp-bg-thead">
                                <th width="10%"><?php echo $this->translate('采购单号'); ?>-<?php echo $this->translate('订单数：').$this->orderList->getTotalItemCount(); ?></th>
                                <th width="15%"><?php echo $this->translate('供应商'); ?></th>
                                <th width="10%"><?php echo $this->translate('联系人'); ?></th>
                                <th width="10%"><?php echo $this->translate('联系电话'); ?></th>
                                <th width="10%"><?php echo $this->translate('退货金额'); ?></th>
                                <th width="6%"><?php echo $this->translate('状态'); ?></th>
                                <th width="15%"><?php echo $this->translate('操作'); ?></th>
                            </tr>
                            <?php
                            $sForm = $this->searchForm;
                            $sForm->prepare();
                            $sForm->get('return_state')->setEmptyOption('选择');
                            ?>
                            <?php echo $this->form()->openTag($sForm); ?>
                            <tr>
                                <td>
                                    <?php echo $this->formElement($sForm->get('p_order_sn')); ?>
                                    <?php echo $this->formElementErrors($sForm->get('p_order_sn'), ['class'=>'error-message']);?>
                                </td>
                                <td>
                                    <?php echo $this->formElement($sForm->get('supplier_id')); ?>
                                    <?php echo $this->formElementErrors($sForm->get('supplier_id'), ['class'=>'error-message']);?>
                                </td>
                                <td>
                                    <?php echo $this->formElement($sForm->get('supplier_contacts')); ?>
                                    <?php echo $this->formElementErrors($sForm->get('supplier_contacts'), ['class'=>'error-message']);?>
                                </td>
                                <td>
                                    <?php echo $this->formElement($sForm->get('supplier_phone')); ?>
                                    <?php echo $this->formElementErrors($sForm->get('supplier_phone'), ['class'=>'error-message']);?>
                                </td>
                                <td>
                                    <p>
                                        <?php echo $this->formElement($sForm->get('start_amount')); ?>
                                    </p>
                                    <div>
                                        <?php echo $this->formElement($sForm->get('end_amount')); ?>
                                    </div>
                                    <?php echo $this->formElementErrors($sForm->get('start_amount'), ['class'=>'error-message']);?>
                                    <?php echo $this->formElementErrors($sForm->get('end_amount'), ['class'=>'error-message']);?>
                                </td>
                                <td>
                                    <?php echo $this->formElement($sForm->get('return_state')); ?>
                                    <?php echo $this->formElementErrors($sForm->get('return_state'), ['class'=>'error-message']);?>
                                </td>
                                <td>
                                    <button type="submit" class="btn btn-info btn-sm"><i class="fa fa-search"></i></button>
                                    <?php if(!empty(array_filter($sForm->getData()))) { ?>
                                        <a href="<?php echo $this->url('order-return');?>" class="btn btn-default btn-sm"><i class="fa fa-reply"></i></a>
                                    <?php } ?>
                                </td>
                            </tr>
                            <?php echo $this->form()->closeTag(); ?>
                            </thead>

                            <?php if($this->orderList) foreach ($this->orderList as $order) { ?>
                                <tr>
                                    <td><?php echo $this->escapeHtml($order->getPorderSn()); ?></td>
                                    <td><?php echo $this->escapeHtml($order->getOnePOrder()->getOneSupplier()->getSupplierName()); ?></td>
                                    <td><?php echo $this->escapeHtml($order->getOnePOrder()->getSupplierContacts()); ?></td>
                                    <td><?php echo $this->escapeHtml($order->getOnePOrder()->getSupplierPhone()); ?></td>
                                    <td><?php echo $this->erpCurrencyFormat($order->getPOrderReturnAmount());?></td>
                                    <td><?php echo $this->PurchaseHelper()->orderReturnState($order->getReturnState(), 2); ?></td>
                                    <td>
                                        <a href="<?php echo $this->url('order-return',
                                            ['action'=>'view', 'id'=>$order->getOrderReturnId()]); ?>" class="btn btn-xs btn-info"><i class="fa fa-info-circle"></i> <?php echo $this->translate('查看'); ?></a>
                                        <?php if($order->getReturnState() == -1) { ?>
                                            <a href="<?php echo $this->url('order-return',
                                                ['action'=>'returnFinish', 'id'=>$order->getOrderReturnId()], ['query' => ['qToken' => $this->common()->getCsrfValue()]]); ?>" class="btn btn-xs btn-success"><i class="fa fa-check"></i> <?php echo $this->translate('退货完成'); ?></a>
                                            <a href="<?php echo $this->url('order-return',
                                                ['action'=>'cancel', 'id'=>$order->getOrderReturnId()], ['query' => ['qToken' => $this->common()->getCsrfValue()]]); ?>" class="btn btn-xs btn-warning"><i class="fa fa-remove"></i> <?php echo $this->translate('取消退货'); ?></a>
                                        <?php } ?>

                                    </td>
                                </tr>
                            <?php } ?>
                        </table>
                    </div>
                    <div class="box-footer clearfix">
                        <?php echo $this->paginationControl($this->orderList, 'Sliding', 'layout/page', ['route' => 'order-return']); ?>
                    </div>
                </div>

            </div>
        </div>

    </section>
</div>