<?php
$form = $this->form;
$form->prepare();
?>
<div class="content-wrapper">
    <?php echo $this->form()->openTag($form); ?>
    <section class="content-header">
        <?php echo $this->partial('layout/breadcrumb'); ?>

        <h1 class="pull-right">
            <a href="<?php echo $this->url('p-order');?>" class="btn btn-default btn-sm"><i class="fa fa-arrow-left"></i> <?php echo $this->translate('返回采购订单列表'); ?></a>
            <button type="submit" class="btn btn-primary btn-sm"><i class="fa fa-check"></i> <?php echo $this->translate('点击退货'); ?></button>
            <?php echo $this->HelpUrl('orderReturnAdd'); ?>
        </h1>
    </section>

    <section class="content">

        <div class="row">
            <div class="col-md-12">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title"><?php echo $this->translate('订单信息');?></h3>
                    </div>

                    <div class="box-body">
                        <?php echo $this->formElementErrors($form->get('dberp_csrf'), ['class'=>'error-message']); ?>
                        <div class="row">
                            <div class="col-xs-4 form-group">
                                <div class="col-sm-12">
                                    <b><?php echo $this->translate('采购单号'); ?>：</b><?php echo $this->escapeHtml($this->orderInfo->getPOrderSn());?>
                                </div>
                            </div>

                            <div class="col-xs-4 form-group">
                                <div class="col-sm-12">
                                    <b class="text-blue"><?php echo $this->translate('订单金额'); ?>：</b><?php echo $this->erpCurrencyFormat($this->orderInfo->getPOrderAmount());?>
                                </div>
                            </div>

                            <div class="col-xs-4 form-group">
                                <div class="col-sm-12">
                                    <b><?php echo $this->translate('付款方式'); ?>：</b><?php echo $this->PurchaseHelper()->orderPayment($this->orderInfo->getPaymentCode());?>
                                </div>
                            </div>

                        </div>

                        <div class="row">
                            <div class="col-xs-4 form-group">
                                <div class="col-sm-12">
                                    <b><?php echo $this->translate('供应商'); ?>：</b><?php echo $this->escapeHtml($this->orderInfo->getOneSupplier()->getSupplierName());?>
                                </div>
                            </div>

                            <div class="col-xs-4 form-group">
                                <div class="col-sm-12">
                                    <b><?php echo $this->translate('供应商联系人'); ?>：</b><?php echo $this->escapeHtml($this->orderInfo->getSupplierContacts());?>
                                </div>
                            </div>

                            <div class="col-xs-4 form-group">
                                <div class="col-sm-12">
                                    <b><?php echo $this->translate('供应商手机'); ?>：</b><?php echo $this->escapeHtml($this->orderInfo->getSupplierPhone());?>
                                </div>
                            </div>

                        </div>

                        <div class="row">
                            <div class="col-xs-4 form-group">
                                <div class="col-sm-12">
                                    <b><?php echo $this->translate('供应商座机'); ?>：</b><?php echo $this->escapeHtml($this->orderInfo->getSupplierTelephone());?>
                                </div>
                            </div>
                            <div class="col-xs-8 form-group">
                                <div class="col-sm-12">
                                    <b><?php echo $this->translate('备注'); ?>：</b><?php echo $this->escapeHtml($this->orderInfo->getPOrderInfo());?>
                                </div>
                            </div>

                        </div>

                        <div class="box-header">
                            <h4 class="box-title"><?php echo $this->translate('选择退货商品'); ?></h4>
                            &nbsp;
                            <div>
                                <?php echo $this->formElementErrors($form->get('pGoodsId'), ['class'=>'error-message']); ?>
                                <?php echo $this->formElementErrors($form->get('goodsReturnNum'), ['class'=>'error-message']); ?>
                                <?php echo $this->formElementErrors($form->get('goodsReturnAmount'), ['class'=>'error-message']); ?>
                            </div>
                        </div>
                        <div class="box-body table-responsive no-padding">
                            <table class="table table-hover">
                                <thead>
                                <tr>
                                    <th width="4%"><?php echo $this->translate('选择'); ?></th>
                                    <th width="10%"><?php echo $this->translate('商品编号'); ?></th>
                                    <th width="20%"><?php echo $this->translate('商品名称'); ?></th>
                                    <th width="10%"><?php echo $this->translate('商品规格'); ?></th>
                                    <th width="10%"><?php echo $this->translate('采购单价'); ?></th>
                                    <th width="6%"><?php echo $this->translate('采购数量'); ?></th>
                                    <th width="8%"><?php echo $this->translate('税金'); ?></th>
                                    <th width="10%"><?php echo $this->translate('采购总价'); ?></th>
                                    <th width="8%"><?php echo $this->translate('退货数量'); ?></th>
                                    <th width="12%"><?php echo $this->translate('退货金额'); ?></th>
                                </tr>
                                </thead>
                                <?php
                                foreach ($this->orderGoods as $goodsValue) {
                                    ?>
                                    <tr>
                                        <td><input type="checkbox" title="<?php echo $this->translate('请选择退货商品'); ?>" required minlength="1" name="pGoodsId[]" value="<?php echo $goodsValue->getPGoodsId(); ?>" <?php echo (isset($this->formData['pGoodsId']) && in_array($goodsValue->getPGoodsId(), $this->formData['pGoodsId'])) ? 'checked' : ''?> class="minimal"></td>
                                        <td><?php echo $this->escapeHtml($goodsValue->getGoodsNumber());?></td>
                                        <td><?php echo $this->escapeHtml($goodsValue->getGoodsName());?></td>
                                        <td><?php echo $this->escapeHtml($goodsValue->getGoodsSpec());?></td>
                                        <td><?php echo $this->erpCurrencyFormat($goodsValue->getPGoodsPrice());?><input type="hidden" name="goods_price_<?php echo $goodsValue->getPGoodsId(); ?>" id="goods_price_<?php echo $goodsValue->getPGoodsId(); ?>" value="<?php echo $this->erpCurrencyFormat($goodsValue->getPGoodsPrice(), '');?>"></td>
                                        <td><?php echo $this->escapeHtml($goodsValue->getPGoodsBuyNum());?><?php echo $this->escapeHtml($goodsValue->getGoodsUnit());?></td>
                                        <td><?php echo $this->erpCurrencyFormat($goodsValue->getPGoodsTax());?></td>
                                        <td><?php echo $this->erpCurrencyFormat($goodsValue->getPGoodsAmount());?></td>
                                        <td><input type="number" min="0" max="<?php echo $this->escapeHtml($goodsValue->getPGoodsBuyNum());?>" oninput="returnGoodsPrice(<?php echo $goodsValue->getPGoodsId(); ?>);" name="goodsReturnNum[<?php echo $goodsValue->getPGoodsId(); ?>]" id="goods_return_num_<?php echo $goodsValue->getPGoodsId(); ?>" value="<?php echo isset($this->formData['goodsReturnNum'][$goodsValue->getPGoodsId()]) ? $this->escapeHtml($this->formData['goodsReturnNum'][$goodsValue->getPGoodsId()]) : '0'?>" class="form-control"></td>
                                        <td><input type="text" oninput="returnGoodsPrice(<?php echo $goodsValue->getPGoodsId(); ?>);" name="goodsReturnAmount[<?php echo $goodsValue->getPGoodsId(); ?>]" id="goods_return_amount_<?php echo $goodsValue->getPGoodsId(); ?>" value="<?php echo isset($this->formData['goodsReturnAmount'][$goodsValue->getPGoodsId()]) ? $this->escapeHtml($this->formData['goodsReturnAmount'][$goodsValue->getPGoodsId()]) : '0'?>" class="form-control"></td>
                                    </tr>
                                <?php } ?>
                            </table>
                        </div>
                        <div class="row">
                            <div class="col-xs-12 form-group">
                                <div class="col-sm-12">
                                    <?php echo $this->translate('退货原因'); ?>
                                    <?php echo $this->formElement($form->get('pOrderReturnInfo')); ?>
                                    <?php echo $this->formElementErrors($form->get('pOrderReturnInfo'), ['class'=>'error-message']); ?>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="box-footer">
                        <?php echo $this->formElement($form->get('dberp_csrf')); ?>
                        <button type="submit" class="btn btn-primary col-md-offset-5"><i class="fa fa-check"></i> <?php echo $this->translate('点击退货'); ?></button>
                    </div>
                </div>
            </div>
        </div>

    </section>
    <?php echo $this->form()->closeTag(); ?>
</div>
<script type="text/javascript">
    $(document).ready(function() {
        $("#<?php echo $form->getName(); ?>").validate();
    });

    function returnGoodsPrice(id) {
        var goodsPrice  = $('#goods_price_'+id).val();
        goodsPrice  = goodsPrice == '' ? 0 : parseFloat(goodsPrice);
        var goodsNum    = $('#goods_return_num_'+id).val();
        goodsNum    = goodsNum == '' ? 1 : parseInt(goodsNum);

        var goodsAmount = goodsPrice * goodsNum;

        $('#goods_return_amount_'+id).val(erpNumber(goodsAmount, 2));

        sumAmount();
    }
    function sumAmount() {
    }
</script>