<div class="content-wrapper">
    <?php
    $form = $this->form;
    $form->prepare();

    $form->get('warehouseOrderState')->setEmptyOption('选择状态');

    $form->get('warehouseOrderSn')->setAttributes([
        'placeholder' => $this->translate('入库单号')
    ]);

    $form->get('warehouseOrderInfo')->setAttributes([
        'placeholder' => $this->translate('入库备注')
    ]);
    ?>
    <?php echo $this->form()->openTag($form); ?>
    <section class="content-header">
        <?php echo $this->partial('layout/breadcrumb'); ?>

        <h1 class="pull-right">
            <a href="<?php echo $this->url('p-order');?>" class="btn btn-default btn-sm"><i class="fa fa-arrow-left"></i> <?php echo $this->translate('返回采购单列表'); ?></a>
            <button type="submit" class="btn btn-primary btn-sm"><i class="fa fa-check"></i> <?php echo $this->translate('验货入库'); ?></button>
            <?php echo $this->HelpUrl('warehouseOrderAdd'); ?>
        </h1>
    </section>

    <section class="content">

        <div class="row">
            <div class="col-md-12">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title"><?php echo $this->translate('验货入库处理'); ?></h3>
                    </div>

                    <div class="box-body">
                        <?php echo $this->formElementErrors($form->get('dberp_csrf'), ['class'=>'error-message']); ?>
                        <div class="row">
                            <div class="col-xs-4 form-group">
                                <div class="col-sm-12">
                                    <?php echo $this->translate('入库单号'); ?><span class="must_add_value">*</span>
                                    <?php echo $this->formElement($form->get('warehouseOrderSn')); ?>
                                    <?php echo $this->formElementErrors($form->get('warehouseOrderSn'), ['class'=>'error-message']); ?>
                                </div>
                            </div>

                            <div class="col-xs-4 form-group">
                                <div class="col-sm-12">
                                    <?php echo $this->translate('仓库'); ?><span class="must_add_value">*</span>
                                    <?php echo $this->formElement($form->get('warehouseId')); ?>
                                    <?php echo $this->formElementErrors($form->get('warehouseId'), ['class'=>'error-message']); ?>
                                </div>
                            </div>

                            <div class="col-xs-4 form-group">
                                <div class="col-sm-12">
                                    <?php echo $this->translate('状态'); ?><span class="must_add_value">*</span>
                                    <?php echo $this->formElement($form->get('warehouseOrderState')); ?>
                                    <?php echo $this->formElementErrors($form->get('warehouseOrderState'), ['class'=>'error-message']); ?>
                                </div>
                            </div>

                        </div>

                        <div class="row">
                            <div class="col-xs-12 form-group">
                                <div class="col-sm-12">
                                    <?php echo $this->translate('入库备注'); ?>
                                    <?php echo $this->formElement($form->get('warehouseOrderInfo')); ?>
                                    <?php echo $this->formElementErrors($form->get('warehouseOrderInfo'), ['class'=>'error-message']); ?>
                                </div>
                            </div>
                        </div>

                        <hr />

                        <div class="row">
                            <div class="col-xs-4 form-group">
                                <div class="col-sm-12">
                                    <b><?php echo $this->translate('采购单号'); ?>：</b><?php echo $this->escapeHtml($this->orderInfo->getPOrderSn());?>
                                </div>
                            </div>

                            <div class="col-xs-4 form-group">
                                <div class="col-sm-12">
                                    <b><?php echo $this->translate('供应商'); ?>：</b><?php echo $this->escapeHtml($this->orderInfo->getOneSupplier()->getSupplierName());?>
                                </div>
                            </div>

                            <div class="col-xs-4 form-group">
                                <div class="col-sm-12">
                                    <b><?php echo $this->translate('付款方式'); ?>：</b><?php echo $this->PurchaseHelper()->orderPayment($this->orderInfo->getPaymentCode());?>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-xs-4 form-group">
                                <div class="col-sm-12">
                                    <b><?php echo $this->translate('供应商联系人'); ?>：</b><?php echo $this->escapeHtml($this->orderInfo->getSupplierContacts());?>
                                </div>
                            </div>

                            <div class="col-xs-4 form-group">
                                <div class="col-sm-12">
                                    <b><?php echo $this->translate('供应商手机'); ?>：</b><?php echo $this->escapeHtml($this->orderInfo->getSupplierPhone());?>
                                </div>
                            </div>

                            <div class="col-xs-4 form-group">
                                <div class="col-sm-12">
                                    <b><?php echo $this->translate('供应商座机'); ?>：</b><?php echo $this->escapeHtml($this->orderInfo->getSupplierTelephone());?>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-xs-12 form-group">
                                <div class="col-sm-12">
                                    <b><?php echo $this->translate('备注'); ?>：</b><?php echo $this->escapeHtml($this->orderInfo->getPOrderInfo());?>
                                </div>
                            </div>
                        </div>

                        <div class="box-header">
                            <h4 class="box-title"><?php echo $this->translate('采购商品'); ?></h4>
                        </div>
                        <div class="box-body table-responsive no-padding">
                            <table class="table table-hover">
                                <thead>
                                <tr>
                                    <th width="15%"><?php echo $this->translate('商品编号'); ?></th>
                                    <th><?php echo $this->translate('商品名称'); ?></th>
                                    <th><?php echo $this->translate('商品规格'); ?></th>
                                    <th width="10%"><?php echo $this->translate('采购单价'); ?></th>
                                    <th width="10%"><?php echo $this->translate('采购数量'); ?></th>
                                    <th width="10%"><?php echo $this->translate('采购总价'); ?></th>
                                </tr>
                                </thead>
                                <?php foreach ($this->orderGoods as $goodsValue) { ?>
                                <tr>
                                    <td><?php echo $this->escapeHtml($goodsValue->getGoodsNumber()); ?></td>
                                    <td><?php echo $this->escapeHtml($goodsValue->getGoodsName()); ?></td>
                                    <td><?php echo $this->escapeHtml($goodsValue->getGoodsSpec()); ?></td>
                                    <td><?php echo $this->erpCurrencyFormat($goodsValue->getPGoodsPrice()); ?></td>
                                    <td><?php echo $goodsValue->getPGoodsBuyNum(); ?></td>
                                    <td><?php echo $this->erpCurrencyFormat($goodsValue->getPGoodsAmount()); ?></td>
                                </tr>
                                <?php } ?>
                            </table>
                        </div>

                    </div>
                    <div class="box-footer">
                        <?php echo $this->formElement($form->get('dberp_csrf')); ?>
                        <button type="submit" class="btn btn-primary col-md-offset-4"><i class="fa fa-check"></i> <?php echo $this->translate('验货入库'); ?></button>
                    </div>
                </div>


            </div>
        </div>

    </section>
    <?php echo $this->form()->closeTag(); ?>

</div>
<script type="text/javascript">
    $(document).ready(function() {
        $("#<?php echo $form->getName(); ?>").validate({
            rules: {
                warehouseOrderSn: {
                    required: true
                },
                warehouseId: {
                    required: true,
                    min: 1
                },
                warehouseOrderState: {
                    required: true
                }
            },
            messages: {
                warehouseOrderSn: {
                    required: "<?php echo $this->translate('入库单号不能为空！'); ?>"
                },
                warehouseId: {
                    required: "<?php echo $this->translate('请选择仓库！'); ?>",
                    min: "<?php echo $this->translate('请选择仓库！'); ?>"
                },
                warehouseOrderState: {
                    required: "<?php echo $this->translate('请选择状态！'); ?>"
                }
            }
        });
    });
</script>