<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Language" content="zh-CN">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <?php
    $this->headtitle('DBERP 进销存系统');
    $this->headtitle('Powered by 珑大软件');
    echo $this->headTitle()->setSeparator(' - ');

    $this->headMeta()->appendName('author', '北京珑大钜商科技有限公司');
    $this->headMeta()->appendName('copyright', 'DBErp Inc. All Rights Reserved');

    $this->headMeta()->setAutoEscape(false);

    echo $this->headMeta();
    ?>
    <link rel="icon" href="<?php echo $this->basePath('favicon.ico'); ?>">
    <link rel="stylesheet" href="<?php echo $this->basePath('css/bootstrap/css/bootstrap.min.css'); ?>">
    <link rel="stylesheet" href="<?php echo $this->basePath('css/font-awesome/css/font-awesome.min.css'); ?>">
    <link rel="stylesheet" href="<?php echo $this->basePath('css/Ionicons/css/ionicons.min.css'); ?>">
    <link rel="stylesheet" href="<?php echo $this->basePath('js/plugins/iCheck/all.css'); ?>">
    <link rel="stylesheet" href="<?php echo $this->basePath('css/admin/css/AdminLTE.css'); ?>">

    <link rel="stylesheet" href="<?php echo $this->basePath('css/admin/css/skins/_all-skins.min.css'); ?>">
    <link rel="stylesheet" href="<?php echo $this->basePath('css/admin/css/stylesheet.css'); ?>">

    <!--[if lt IE 9]>
    <script src="<?php echo $this->basePath('js/html5shiv.min.js'); ?>"></script>
    <script src="<?php echo $this->basePath('js/respond.min.js'); ?>"></script>
    <![endif]-->

    <script src="<?php echo $this->basePath('js/jquery.min.js'); ?>"></script>
    <!-- Bootstrap 3.3.7 -->
    <script src="<?php echo $this->basePath('css/bootstrap/js/bootstrap.min.js'); ?>"></script>
    <!-- iCheck -->
    <script src="<?php echo $this->basePath('js/plugins/iCheck/icheck.min.js'); ?>"></script>
    <script src="<?php echo $this->basePath('js/adminlte.js'); ?>"></script>

    <script src="<?php echo $this->basePath('js/plugins/jquery-validation/jquery.validate.js'); ?>"></script>
    <script src="<?php echo $this->basePath('js/plugins/jquery-validation/additional-methods.js'); ?>" ></script>

    <script src="<?php echo $this->basePath('js/plugins/layer/layer.js'); ?>" ></script>
    <script src="<?php echo $this->basePath('js/plugins/laydate/laydate.js'); ?>" ></script>

    <script src="<?php echo $this->basePath('js/plugins/echarts/echarts.min.js'); ?>"></script>
    <script src="<?php echo $this->basePath('js/plugins/echarts/theme/shine.js'); ?>"></script>

    <script src="<?php echo $this->basePath('js/plugins/jquery-number/jquery.number.min.js'); ?>"></script>
    <script src="<?php echo $this->basePath('js/plugins/jquery-print/jquery.jqprint-0.3.js'); ?>"></script>

    <script src="<?php echo $this->basePath('js/headCommon.js'); ?>?t=<?php echo time(); ?>"></script>

</head>
<?php
$moduleName = $this->module;
$controllerName = $this->controller;
$actionName = $this->action;

$shopServiceState = $this->adminHelper()->erp('shop_service');
?>
<body class="hold-transition skin-purple sidebar-mini <?php if($controllerName == 'HomeController' && !\Admin\Data\Common::isMobile()) echo 'sidebar-collapse'; ?>">
<div class="wrapper">
    <?php echo $this->partial('layout/header', ['moduleName' => $moduleName, 'controllerName' => $controllerName, 'shopServiceState' => $shopServiceState]); ?>
    <?php echo $this->partial('layout/left', ['moduleName' => $moduleName, 'controllerName' => $controllerName, 'shopServiceState' => $shopServiceState]); ?>

    <div class="content-wrapper">
        <section class="content-header">
            <h1>
                <?php echo $this->translate('您无权访问该页面'); ?>
                <small>
                    <?php if (!empty($this->lastPage)) { ?>
                        <a href="<?php echo urldecode($this->lastPage); ?>" class="btn btn-sm btn-primary"><i class="fa fa-reply" aria-hidden="true"></i>&nbsp;&nbsp;<?php echo $this->translate('返回上一页'); ?></a>
                    <?php } else { ?>
                        <a href="<?php echo $this->url('home'); ?>" class="btn btn-sm btn-primary"><i class="fa fa-home" aria-hidden="true"></i>&nbsp;&nbsp;<?php echo $this->translate('返回后台首页'); ?></a>
                    <?php } ?>
                </small>
            </h1>
        </section>
    </div>
    <?php echo $this->partial('layout/footer'); ?>

</div>
<script src="<?php echo $this->basePath('js/common.js'); ?>?t=<?php echo time(); ?>" ></script>
</body>
</html>