<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Language" content="zh-CN">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <?php
    $this->headtitle('DBERP 进销存系统安装');
    $this->headtitle('Powered by 珑大软件');
    echo $this->headTitle()->setSeparator(' - ');

    $this->headMeta()->appendName('author', '北京珑大钜商科技有限公司');
    $this->headMeta()->appendName('copyright', 'DBERP Inc. All Rights Reserved');

    $this->headMeta()->setAutoEscape(false);

    echo $this->headMeta();
    ?>
    <link rel="icon" href="<?php echo $this->basePath('favicon.ico'); ?>">
    <link rel="stylesheet" href="<?php echo $this->basePath('css/bootstrap/css/bootstrap.min.css'); ?>">
    <link rel="stylesheet" href="<?php echo $this->basePath('css/font-awesome/css/font-awesome.min.css'); ?>">
    <script type="text/javascript" src="<?php echo $this->basePath('js/jquery.min.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->basePath('js/plugins/jquery-validation/jquery.validate.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->basePath('js/plugins/jquery-validation/additional-methods.js'); ?>" ></script>

    <script type="text/javascript" src="<?php echo $this->basePath('js/plugins/layer/layer.js'); ?>" ></script>
    <style>
        .navbar-inverse {
            background-color:#605ca8;
            border-color:#605ca8;
            color: #fff;
        }
        .error {
            color: red;
            font-weight: normal;
        }
        .error-message {
            list-style-type: none;
            padding: 0px;
            margin: 0px 5px;
        }

        .error-message li {
            color: red;
        }
    </style>
</head>
<body>
<div class="container">
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" style="color: #fff;" href="https://www.dbshop.net/">DBERP 进销存系统 <?php echo DBERP_VERSION; ?></a>
            </div>
        </div>
    </nav>
</div>
<div class="container" style="margin-top: 70px;">
    <?php echo $this->content;?>
    <div class="row">
        <footer class="text-center">
            <p>© <a href="https://www.loongdom.com.cn/">北京珑大钜商科技有限公司</a></p>
        </footer>
    </div>
</div>

</body>
</html>