<table class="table table-bordered">
    <tr>
        <td>
            <h3>DBERP进销存系统授权协议 适用于所有用户</h3>

            <p>版权所有 (c) 2012-<?php echo date("Y") ?>，DBERP进销存系统产品开发团队保留所有权利。</p>

            <p>感谢您选择 DBERP进销存系统(软件著作权登记号：2019SR1171829)，希望我们的努力能为您提供一个高效、安全、强大的电子商务解决方案。</p>

            <p>本授权协议适用于 DBERP 所有版本，DBERP进销存系统产品开发团队拥有对本授权协议的最终解释权。</p>

            <h4>I. 协议许可的权利</h4>
            <ol>
                <li>您可以在完全遵守本最终用户授权协议的基础上，将本软件应用于非商业用途，而不必支付软件版权授权费用；<strong  style="color:red;">在未获商业授权将本软件用于商业用途，底部必须保留DBERP官方版权信息。</strong></li>
                <li>您可以在协议规定的约束和限制范围内进行部分修改以适应您的网站要求。</li>
                <li>您拥有使用本软件构建的网站中全部会员资料、文章及相关信息的所有权，并独立承担与文章内容的相关法律义务。</li>
                <li>获得商业授权之后，您可以将本软件应用于商业用途，同时依据所购买的授权类型中确定的技术支持期限、技术支持方式和技术支持内容，自购买时刻起，在技术支持期限内拥有通过指定的方式获得指定范围内的技术支持服务。商业授权用户享有反映和提出意见的权力，相关意见将被作为首要考虑，但没有一定被采纳的承诺或保证。</li>
            </ol>

            <h4>II. 协议规定的约束和限制</h4>
            <ol>
                <li>未获商业授权之前，用于商业用途，必须保留底部版权信息，否则不得将本软件用于商业用途（包括但不限于企业网站、经营性网站、以营利为目或实现盈利的网站）。购买商业授权请访问https://www.DBERP.com.cn/参考相关说明。</li>
                <li>不得对本软件或与之关联的商业授权进行出租、出售、抵押或发放子许可证。</li>
                <li>无论如何，即无论用途如何、是否经过修改或美化、修改程度如何，只要使用 DBERP进销存系统 的整体或任何部分，未经书面许可，页面页脚处的 版权信息 的链接都必须保留，而不能清除或修改。</li>
                <li>禁止在 DBERP进销存系统 的整体或任何部分基础上以发展任何派生版本、修改版本或第三方版本用于重新分发。</li>
                <li>如果您未能遵守本协议的条款，您的授权将被终止，所被许可的权利将被收回，并承担相应法律责任。</li>
            </ol>

            <h4>III. 有限担保和免责声明</h4>
            <ol>
                <li>本软件及所附带的文件是作为不提供任何明确的或隐含的赔偿或担保的形式提供的。</li>
                <li>用户出于自愿而使用本软件，您必须了解使用本软件的风险，在尚未购买产品技术服务之前，我们不承诺提供任何形式的技术支持、使用担保，也不承担任何因使用本软件而产生问题的相关责任。</li>
                <li>DBERP进销存系统开发团队不对使用本软件构建的网站中的文章或信息承担责任。</li>
            </ol>

            <p>有关 DBERP进销存系统 最终用户授权协议、商业授权与技术服务的详细内容，均由 DBERP 官方网站独家提供。DBERP产品开发团队拥有在不事先通知的情况下，修改授权协议和服务价目表的权力，修改后的协议或价目表对自改变之日起的新授权用户生效。</p>

            <p>电子文本形式的授权协议如同双方书面签署的协议一样，具有完全的和等同的法律效力。您一旦开始安装 DBERP 产品，即被视为完全理解并接受本协议的各项条款，在享有上述条款授予的权力的同时，受到相关的约束和限制。协议许可范围以外的行为，将直接违反本授权协议并构成侵权，我们有权随时终止授权，责令停止损害，并保留追究相关责任的权力。</p>

        </td>
    </tr>
</table>
<div class="row">
    <p class="text-center">
        <a href="<?php echo $this->url('erp-install', ['action' => 'nextStep']); ?>" class="btn btn-large btn-primary"><i class="fa fa-check" aria-hidden="true"></i> <?php echo $this->translate('同意协议，继续安装'); ?></a>&nbsp;&nbsp;&nbsp;&nbsp;
        <button type="button" onclick="closeWindow();" class="btn btn-large btn-warning"><i class="fa fa-times" aria-hidden="true"></i> <?php echo $this->translate('不同意协议，取消安装'); ?></button>
    </p>
</div>

<script type="text/javascript">
    function closeWindow() {
        let userAgent = navigator.userAgent;
        if (userAgent.indexOf("Firefox") != -1 || userAgent.indexOf("Chrome") != -1) {
            location.href = "about:blank";
        } else {
            window.opener = null;
            window.open('', '_self');
        }
        window.close();
    }
</script>