<div class="content-wrapper">
    <section class="content-header">
        <?php echo $this->partial('layout/breadcrumb'); ?>
    </section>

    <section class="content">

        <div class="row">
            <div class="col-lg-3 col-xs-6">
                <div class="small-box bg-aqua">
                    <div class="inner">
                        <h3><?php echo $this->salesOrderCount?></h3>

                        <p><?php echo $this->translate('订单总数'); ?></p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-bag"></i>
                    </div>
                    <p class="small-box-footer"><?php echo $this->translate('系统订单'); ?> + <?php echo $this->translate('商城订单'); ?></p>
                </div>
            </div>

            <div class="col-lg-3 col-xs-6">
                <div class="small-box bg-green">
                    <div class="inner">
                        <h3><?php echo $this->erpCurrencyFormat($this->salesAmount); ?></h3>

                        <p><?php echo $this->translate('订单总金额'); ?></p>
                    </div>
                    <div class="icon">
                        <i class="fa fa-cny"></i>
                    </div>
                    <p class="small-box-footer"><?php echo $this->translate('系统订单金额'); ?> + <?php echo $this->translate('商城订单金额'); ?></p>
                </div>
            </div>

            <div class="col-lg-3 col-xs-6">
                <div class="small-box bg-yellow">
                    <div class="inner">
                        <h3><?php echo $this->customerCount?></h3>

                        <p><?php echo $this->translate('下单客户'); ?></p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-person-add"></i>
                    </div>
                    <p class="small-box-footer"><?php echo $this->translate('唯一客户数'); ?></p>
                </div>
            </div>

            <div class="col-lg-3 col-xs-6">
                <div class="small-box bg-red">
                    <div class="inner">
                        <h3><?php echo $this->goodsCount?></h3>

                        <p><?php echo $this->translate('销售商品数'); ?></p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-pie-graph"></i>
                    </div>
                    <p class="small-box-footer"><?php echo $this->translate('唯一商品数'); ?></p>
                </div>
            </div>

        </div>

    </section>

</div>