<div class="content-wrapper">

    <section class="content-header">
        <?php echo $this->partial('layout/breadcrumb'); ?>

        <h1 class="pull-right">
            <a href="<?php echo $this->url('supplier', ['action'=> 'add']);?>" class="btn btn-primary btn-sm"><i class="fa fa-plus"></i> <?php echo $this->translate('添加供应商'); ?></a>
            <?php echo $this->HelpUrl('supplierList'); ?>
        </h1>

    </section>

    <section class="content">
        <?php echo $this->partial('layout/messages'); ?>

        <div class="row">
            <div class="col-xs-12">
                <div class="box erp-box">

                    <div class="box-body table-responsive no-padding">
                            <table class="table table-hover">
                                <thead>
                                <tr class="erp-bg-thead">
                                    <th width="2%"><input type="checkbox" class="minimal select-all-checkbox"></th>
                                    <th width="5%">ID</th>
                                    <th width="20%"><?php echo $this->translate('供应商名称'); ?></th>
                                    <th><?php echo $this->translate('供应商编码'); ?></th>
                                    <th><?php echo $this->translate('供应商联系人'); ?></th>
                                    <th width="15%"><?php echo $this->translate('供应商电话 / 手机'); ?></th>
                                    <th><?php echo $this->translate('供应商分类'); ?></th>
                                    <th width="8%"><?php echo $this->translate('排序'); ?></th>
                                    <th width="12%"><?php echo $this->translate('操作'); ?></th>
                                </tr>

                                <?php
                                $sForm = $this->searchForm;
                                $sForm->prepare();
                                ?>
                                <?php echo $this->form()->openTag($sForm); ?>
                                <tr>
                                    <td></td>
                                    <td>
                                        <p>
                                            <?php echo $this->formElement($sForm->get('start_id')); ?>
                                        </p>
                                        <div>
                                            <?php echo $this->formElement($sForm->get('end_id')); ?>
                                        </div>
                                        <?php echo $this->formElementErrors($sForm->get('start_id'), ['class'=>'error-message']);?>
                                        <?php echo $this->formElementErrors($sForm->get('end_id'), ['class'=>'error-message']);?>
                                    </td>
                                    <td>
                                        <?php echo $this->formElement($sForm->get('supplier_name')); ?>
                                        <?php echo $this->formElementErrors($sForm->get('supplier_name'), ['class'=>'error-message']);?>
                                    </td>
                                    <td>
                                        <?php echo $this->formElement($sForm->get('supplier_code')); ?>
                                        <?php echo $this->formElementErrors($sForm->get('supplier_code'), ['class'=>'error-message']);?>
                                    </td>
                                    <td>
                                        <?php echo $this->formElement($sForm->get('supplier_contacts')); ?>
                                        <?php echo $this->formElementErrors($sForm->get('supplier_contacts'), ['class'=>'error-message']);?>
                                    </td>
                                    <td>
                                        <?php echo $this->formElement($sForm->get('supplier_phone')); ?>
                                        <?php echo $this->formElementErrors($sForm->get('supplier_phone'), ['class'=>'error-message']);?>
                                    </td>
                                    <td>
                                        <?php echo $this->formElement($sForm->get('supplier_category_id')); ?>
                                        <?php echo $this->formElementErrors($sForm->get('supplier_category_id'), ['class'=>'error-message']);?>
                                    </td>
                                    <td></td>
                                    <td>
                                        <button type="submit" class="btn btn-info btn-sm"><i class="fa fa-search"></i></button>
                                        <?php if(!empty(array_filter($sForm->getData()))) { ?>
                                            <a href="<?php echo $this->url('supplier');?>" class="btn btn-default btn-sm"><i class="fa fa-reply"></i></a>
                                        <?php } ?>
                                    </td>
                                </tr>
                                <?php echo $this->form()->closeTag(); ?>
                                </thead>

                                <form method="post" action="<?php echo $this->url('supplier', ['action' => 'updateAll']);?>" name="edit-all-form" id="edit-all-form">
                                <?php if($this->supplierList) foreach ($this->supplierList as $supplier) { ?>
                                    <tr>
                                        <td><input  name="select_id[]" value="<?php echo $supplier->getSupplierId(); ?>" type="checkbox" class="minimal"></td>
                                        <td><?php echo $supplier->getSupplierId(); ?></td>
                                        <td><?php echo $this->escapeHtml($supplier->getSupplierName()); ?></td>
                                        <td><?php echo $this->escapeHtml($supplier->getSupplierCode()); ?></td>
                                        <td><?php echo $this->escapeHtml($supplier->getSupplierContacts()); ?></td>
                                        <td><?php echo $this->escapeHtml($supplier->getSupplierTelephone() . ' / ' . $supplier->getSupplierPhone()); ?></td>
                                        <td><?php echo $this->escapeHtml($supplier->getSupplierCategory()->getSupplierCategoryName()); ?></td>
                                        <td><input type="text" name="supplier_sort[<?php echo $supplier->getSupplierId(); ?>]" value="<?php echo $supplier->getSupplierSort(); ?>" class="form-control input-sm"></td>
                                        <td>
                                            <a href="<?php echo $this->url('supplier',
                                                ['action'=>'edit', 'id'=>$supplier->getSupplierId()]); ?>"
                                               class="btn btn-xs btn-success"><i class="fa fa-pencil"></i> <?php echo $this->translate('编辑'); ?>
                                            </a>

                                            <a href="javascript:;" onclick="deleteConfirm('<?php echo $this->translate('您确实要删除该供应商吗？'); ?>', '<?php echo $this->url('supplier', ['action'=>'delete', 'id'=>$supplier->getSupplierId()], ['query' => ['qToken' => $this->common()->getCsrfValue()]]); ?>');" class="btn btn-xs btn-danger">
                                                <i class="fa fa-trash"></i> <?php echo $this->translate('删除'); ?>
                                            </a>

                                        </td>
                                    </tr>
                                <?php } ?>

                                <tfoot>
                                <tr>
                                    <td colspan="9">
                                        <input type="checkbox" class="minimal select-all-checkbox"> <?php echo $this->translate('全选'); ?>
                                        <select name="editAllState" class="form-control input-sm" style="width: 120px;display: inline;">
                                            <option value=""><?php echo $this->translate('选择状态'); ?></option>
                                            <option value="sort"><?php echo $this->translate('更新排序'); ?></option>
                                        </select>
                                        <button type="submit" class="btn btn-primary btn-sm"><i class="fa fa-check"></i> <?php echo $this->translate('更新'); ?></button>
                                        <?php echo $this->paginationControl($this->supplierList,
                                            'Sliding',
                                            'layout/page',
                                            ['route' => 'supplier']); ?>
                                    </td>
                                </tr>
                                </tfoot>
                                </form>
                            </table>

                    </div>

                </div>

            </div>
        </div>

    </section>
</div>